name: Terraform Dev Deploy 
on: pull_request:
  branches:
    - develop
jobs:
    plan: 
        runs-on: ubuntu-latest
        steps:
            - name: Check Repo 
              uses: actions/checkout@v4
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.8.5
            - name: AWS access using OIDC    
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::793291932898:role/github-fritz-oidc
                role-session-name: github-actions
                aws-region: us-east-1
            - name: Terraform Init
              run: terraform init
            - name: Terraform Validate
              run: terraform validate
            - name: Terraform Plan
              run: terraform plan   

